Removed references to DIRECTORY from bin/string-in-file

diff --git a/bin/string-in-file b/bin/string-in-file
--- a/bin/string-in-file
+++ b/bin/string-in-file
@@ -11,18 +11,14 @@ STR1=$3
 STR2=$4
 
 if [ "$MODE" = 'replace' ]; then
-  echo "Replacing '$STR1' with '$STR2' in $DIRECTORY"
-  find $DIRECTORY -type f -exec sed -i "s/$STR1/$STR2/g" {} +
+  sed -i "s/$STR1/$STR2/g" "$FILENAME"
 elif [ "$MODE" = 'error-if-present' ]; then
-  for FILENAME in $(find $DIRECTORY -type f);
-  do
-    if grep -q "$STR1" "$FILENAME"; then
-      echo "The file $FILENAME still contains:"
-      echo "$STR1"
-      echo 'This is against expectations and constitutes an error.'
-      exit 1
-    fi
-  done;
+  if grep -q "$STR1" "$FILENAME"; then
+    echo "The file $FILENAME still contains:"
+    echo "$STR1"
+    echo 'This is against expectations and constitutes an error.'
+    exit 1
+  fi
 elif [ "$MODE" = 'list' ]; then # NOTE: throws error if no files have $STR1
   echo '-----------------------------------------------------'
   echo "BEGIN: list of files containing '$STR1' in $DIRECTORY"
